# -*- coding: utf-8 -*-
"""ipl_batting_stats_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhmMZkkyLVZTQ--fHT1v_sX7krDTRazc
"""

import pandas as pd
import json
batting=pd.read_csv("/content/ipl_batting_career_progression.csv")
batting
print(batting.head())
print(batting.info())
print(batting.shape)
print(batting.describe())
batting.isna().sum()

batting["runs_per_innings"]=batting["runs_scored"]/batting["innings"]
print(batting["runs_per_innings"])
batting["dismissed"]= batting["innings"]-batting["not_outs"]
batting["batting_average"]=batting["runs_scored"]/batting["dismissed"]
print(batting["batting_average"])
batting["balls_per_innings"]=batting["balls_faced"]/batting["innings"]
print(batting["balls_per_innings"])
batting["strike_rate"]=batting["runs_scored"]/batting["balls_faced"]*100
print(batting["strike_rate"])

batting[
    [
        "player_name",
        "runs_scored",
        "innings",
        "not_outs",
        "runs_per_innings",
        "batting_average",
        "balls_per_innings",
        "strike_rate"
    ]
].head(10)
batting[batting["dismissed"]==0]
batting["batting_average"].isna().sum(), batting["batting_average"].isin([float("inf")]).sum()

batting["boundary_runs"] = batting["fours"]*4 + batting["sixes"]*6
batting["boundary_runs"]
batting["boundary_percentage"] = batting["boundary_runs"]/batting["runs_scored"]*100
batting["boundary_percentage"]

batting.sort_values("runs_scored",ascending=False)[["player_name","runs_scored","innings"]].head(10)
batting.sort_values(
    "strike_rate",
    ascending=False
)[["player_name", "strike_rate", "runs_scored", "innings"]].head(10)

import matplotlib.pyplot as plt

plt.scatter(batting["runs_scored"], batting["strike_rate"])

plt.xlabel("Runs Scored")
plt.ylabel("Strike Rate")
plt.title("Runs vs Strike Rate")

plt.show()

from sklearn.preprocessing import MinMaxScaler
import numpy as np

metrics = [
    "runs_scored",
    "batting_average",
    "strike_rate",
    "runs_per_innings",
    "boundary_percentage"
]

# Replace inf values with NaN for consistency
for col in metrics:
    batting[col] = batting[col].replace([np.inf, -np.inf], np.nan)

# Fill NaN values with 0 before scaling
batting[metrics] = batting[metrics].fillna(0)

scaler = MinMaxScaler()

batting[metrics] = scaler.fit_transform(batting[metrics])
batting["performance_score"] = (
    batting["runs_scored"] * 0.30 +
    batting["batting_average"] * 0.25 +
    batting["strike_rate"] * 0.20 +
    batting["runs_per_innings"] * 0.15 +
    batting["boundary_percentage"] * 0.10
)
batting.sort_values(
    "performance_score",
    ascending=False
)[["player_name", "performance_score"]].head(10)

player = batting[batting["player_name"] == "Virat Kohli"]

player.sort_values("season")[
    ["season", "runs_scored", "batting_average", "strike_rate"]
]
plt.plot(
    player["season"],
    player["runs_scored"],
    marker="o"
)

plt.xlabel("Season")
plt.ylabel("Runs")
plt.title("Career Runs by Season")

plt.show()